### ISSUE TITLE
DataDriven step doesn't work with SUT parameter

### ISSUE THREAD

**Issue by Rafimr** [Top-Q/jsystem#256]
Executing scenario with datadriven step that gets the data file location (path) from the SUT (has an SUT parameter) doesn't work on JSystem 6.1.02.

Steps to reproduce:
1) Install JSystem 6.1.02 with JDK7.
2) Create a new scenario with a datadriven step.
3) Get the datadriven file location from your SUT (for example - ${sut:winMachinesCSVFile}).
4) Run scenario.

**Comment by itaiag** [comment]
This problem is not reproduced in JSystem 6.1.04. 
**Environment:**

* Oracle Java 8 64 bit
* Ubuntu

**Steps**
Using the the example project
* Created a CSV file with a single column. The title is *param0* and the value is string *${sut:station/userName}*
* Used a datadriven BB
* Dragged to the datadriven BB the BB *testWithParameters*
* As the *str* parameter value, used *param0*
* Changed to the sut with name *mystation.xml*
* Executed the scenario

Result
* The value from the SUT was printed correctly.
